# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(df3699fa-8bd2-40b3-9311-f47bd77c9b36)'
    subscriptionId: 'df3699fa-8bd2-40b3-9311-f47bd77c9b36'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'cloud-shell-storage-centralindia'
    location: 'East Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Kratika28-agr/MyRepo/main/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'